apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-vip1
spec:
 replicas: 1
 selector:
   name: nginx-vip1
 template:
   metadata:
     labels:
       name: nginx-vip1
   spec:
     containers:
       - name: nginx-vip1
         image: nginx
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 80
