---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: romana-services
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: romana-services
    spec:
      nodeSelector:
        kubeadm.alpha.kubernetes.io/role: master
      hostNetwork: true
      containers:
      - name: romana-datastore
        image: mysql:5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: romana
        volumeMounts:
        - name: db-path
          mountPath: /var/lib/mysql
      - name: romana-services
        image: pani/romana-services
        imagePullPolicy: IfNotPresent
        args:
        - --cidr=100.112.0.0/16
        - --interface=eth0
        - --namespaces=32
        - --segments=2
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: romana
        volumeMounts:
        - name: log-path
          mountPath: /var/log/romana
      volumes:
      - name: db-path
        hostPath:
          path: /var/lib/romana/db
      - name: log-path
        hostPath:
          path: /var/log/romana
---
apiVersion: v1
kind: Service
metadata:
  name: romana-root
  namespace: kube-system
spec:
  clusterIP: 10.99.99.99
  ports:
  - name: root
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: romana-services
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: romana-agent
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: romana-agent
    spec:
      hostNetwork: true
      containers:
      - name: romana-agent
        image: pani/romana-agent
        imagePullPolicy: IfNotPresent
        args:
        - --romana-root=http://10.99.99.99:9600
        - --cluster-ip-cidr=10.96.0.0/12
        - --cni-image=pani/romana-cni
        - --interface=eth0
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-usr-local-bin
          mountPath: /host/usr/local/bin
        - name: host-etc-romana
          mountPath: /host/etc/romana
        - name: host-cni-bin
          mountPath: /host/opt/cni/bin
        - name: host-cni-net-d
          mountPath: /host/etc/cni/net.d
        - name: log-path
          mountPath: /var/log/romana
      volumes:
      - name: host-usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: host-etc-romana
        hostPath:
          path: /etc/romana
      - name: host-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: host-cni-net-d
        hostPath:
          path: /etc/cni/net.d
      - name: log-path
        hostPath:
          path: /var/log/romana
