---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: romana-services
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: romana-services
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-99-10
      hostNetwork: true
      containers:
      - name: romana-datastore
        image: mysql:5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: romana
        volumeMounts:
        - name: db-path
          mountPath: /var/lib/mysql
      - name: romana-services
        image: cgilmour/romana-services:release-v0.9.3
        imagePullPolicy: Always
        args:
        - --cidr=10.0.0.0/10
        - --interface=eth0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: romana
        volumeMounts:
        - name: log-path
          mountPath: /var/log/romana
      volumes:
      - name: db-path
        hostPath:
          path: /var/lib/romana/db
      - name: log-path
        hostPath:
          path: /var/log/romana
---
apiVersion: v1
kind: Service
metadata:
  name: romana-root
  namespace: kube-system
spec:
  ports:
  - name: root
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: romana-services
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: romana-agent
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: romana-agent
    spec:
      hostNetwork: true
      containers:
      - name: romana-agent
        image: cgilmour/romana-agent:release-v0.9.3
        imagePullPolicy: Always
        args:
        - --romana-root=http://192.168.99.10:9600
        - --cluster-ip-cidr=10.128.0.0/10
        - --cni-image=cgilmour/romana-cni:release-v0.9.3
        - --interface=eth0
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-usr-local-bin
          mountPath: /host/usr/local/bin
        - name: host-etc-romana
          mountPath: /host/etc/romana
        - name: host-cni-bin
          mountPath: /host/opt/cni/bin
        - name: host-cni-net-d
          mountPath: /host/etc/cni/net.d
        - name: log-path
          mountPath: /var/log/romana
      volumes:
      - name: host-usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: host-etc-romana
        hostPath:
          path: /etc/romana
      - name: host-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: host-cni-net-d
        hostPath:
          path: /etc/cni/net.d
      - name: log-path
        hostPath:
          path: /var/log/romana
